### PR TITLE
static generation won't leak js messaging

### PR DESCRIPTION
**Pull request by phoffer**
This makes it so that using Buster to statically generate a blog with this theme won't leak js into pages.
Resolves issue #13 

Fix is taken from [this SO answer](http://stackoverflow.com/a/236106/366051)

### CODE REVIEW

**Comment by unwitting** [comment]
Should we not replace all the <> around script tags instead of just the one on the trailing tag?

**Comment by phoffer** [comment]
I can make that change if you'd like. It would really be your preference; it's not necessary for it to work though. Multiple opening tags don't have any impact; it's just the first closing tag that is processed, which closes everything.

**Comment by unwitting** [comment]
I'd make the change - now that you've brought the question of things
parsing the output to mind I'd feel safer escaping it all :)

**Comment by phoffer** [comment]
No problem! I just pushed those changes. Thanks!

**Comment by unwitting** [comment]
Pulled :)

**Pull request merged**
