### PR TITLE
Added tag description

### PR DESCRIPTION
**Pull request by THS-on**
Instead of "a collection by" you now see the tag description.

THS-on

### CODE REVIEW

**Comment by unwitting** [comment]
Hi, sorry - I've been away from access for a while. This is a good idea, but we need to check whether or not the {{description}} exists, and fall back to the current "a collection by..." if not.

**Comment by THS-on** [comment]
This is a good idea, I'll look how to implement this function.

THS-on

**Comment by unwitting** [comment]
As above, I've closed this up in 8dea53e :)

**Comment by THS-on** [comment]
Nice to see you back working on the theme. I use it for my blog and it's really nice.

**Comment by unwitting** [comment]
:) it hasn't got the love it deserves recently due to a whole bunch of things. It's awesome that you use it and like it! Version 1 will bring a proper public page for it and a newsletter you'll be able to sign up to to get updates. Nearly here!

**Pull request closed without merging**
